---
name: "Newsletters"
guid: "60f478ab-2dd6-4ea0-af10-04d033f75979"
imageUrl: "https://raw.githubusercontent.com/solidsnake1298/Jellyfin-Newsletter-Plugin/master/logo.png"
version: "1.0.0.1"
targetAbi: "10.11.0.0"
framework: "net9.0"
overview: "Send newsletters for recently added media"
description: "This plugin automacially scans a users library (default every 4 hours), populates a list of recently added (not previously scanned) media, converts that data into HTML format, and sends out emails to a provided list of recipients."
category: "General"
owner: "jellyfin"
artifacts:
  - "Jellyfin.Plugin.Newsletters.dll"
  - "SQLitePCL.pretty.dll"
changelog: >
  - If imgPath is null, replace with black square.  Unlikely with proper content, possible with liveTV content.
  FULL CHANGELOG: https://raw.githubusercontent.com/solidsnake1298/Jellyfin-Newsletter-Plugin/master/CHANGELOG.md
